// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_outs.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "get_outs.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace safex {

namespace {

const ::google::protobuf::Descriptor* Out_entry_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Out_entry_reflection_ = NULL;
const ::google::protobuf::Descriptor* Outs_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Outs_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_get_5fouts_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_get_5fouts_2eproto() {
  protobuf_AddDesc_get_5fouts_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "get_outs.proto");
  GOOGLE_CHECK(file != NULL);
  Out_entry_descriptor_ = file->message_type(0);
  static const int Out_entry_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Out_entry, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Out_entry, unlocked_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Out_entry, height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Out_entry, txid_),
  };
  Out_entry_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Out_entry_descriptor_,
      Out_entry::default_instance_,
      Out_entry_offsets_,
      -1,
      -1,
      -1,
      sizeof(Out_entry),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Out_entry, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Out_entry, _is_default_instance_));
  Outs_descriptor_ = file->message_type(1);
  static const int Outs_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Outs, outs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Outs, status_),
  };
  Outs_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Outs_descriptor_,
      Outs::default_instance_,
      Outs_offsets_,
      -1,
      -1,
      -1,
      sizeof(Outs),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Outs, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Outs, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_get_5fouts_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Out_entry_descriptor_, &Out_entry::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Outs_descriptor_, &Outs::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_get_5fouts_2eproto() {
  delete Out_entry::default_instance_;
  delete Out_entry_reflection_;
  delete Outs::default_instance_;
  delete Outs_reflection_;
}

void protobuf_AddDesc_get_5fouts_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_get_5fouts_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016get_outs.proto\022\005safex\"H\n\tOut_entry\022\013\n\003"
    "key\030\001 \001(\014\022\020\n\010unlocked\030\002 \001(\010\022\016\n\006height\030\003 "
    "\001(\004\022\014\n\004txid\030\004 \001(\014\"6\n\004Outs\022\036\n\004outs\030\001 \003(\0132"
    "\020.safex.Out_entry\022\016\n\006status\030\002 \001(\tb\006proto"
    "3", 161);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "get_outs.proto", &protobuf_RegisterTypes);
  Out_entry::default_instance_ = new Out_entry();
  Outs::default_instance_ = new Outs();
  Out_entry::default_instance_->InitAsDefaultInstance();
  Outs::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_get_5fouts_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_get_5fouts_2eproto {
  StaticDescriptorInitializer_get_5fouts_2eproto() {
    protobuf_AddDesc_get_5fouts_2eproto();
  }
} static_descriptor_initializer_get_5fouts_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Out_entry::kKeyFieldNumber;
const int Out_entry::kUnlockedFieldNumber;
const int Out_entry::kHeightFieldNumber;
const int Out_entry::kTxidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Out_entry::Out_entry()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:safex.Out_entry)
}

void Out_entry::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Out_entry::Out_entry(const Out_entry& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:safex.Out_entry)
}

void Out_entry::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unlocked_ = false;
  height_ = GOOGLE_ULONGLONG(0);
  txid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Out_entry::~Out_entry() {
  // @@protoc_insertion_point(destructor:safex.Out_entry)
  SharedDtor();
}

void Out_entry::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  txid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Out_entry::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Out_entry::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Out_entry_descriptor_;
}

const Out_entry& Out_entry::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_get_5fouts_2eproto();
  return *default_instance_;
}

Out_entry* Out_entry::default_instance_ = NULL;

Out_entry* Out_entry::New(::google::protobuf::Arena* arena) const {
  Out_entry* n = new Out_entry;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Out_entry::Clear() {
// @@protoc_insertion_point(message_clear_start:safex.Out_entry)
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unlocked_ = false;
  height_ = GOOGLE_ULONGLONG(0);
  txid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Out_entry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:safex.Out_entry)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes key = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_key()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_unlocked;
        break;
      }

      // optional bool unlocked = 2;
      case 2: {
        if (tag == 16) {
         parse_unlocked:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &unlocked_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_height;
        break;
      }

      // optional uint64 height = 3;
      case 3: {
        if (tag == 24) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &height_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_txid;
        break;
      }

      // optional bytes txid = 4;
      case 4: {
        if (tag == 34) {
         parse_txid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_txid()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:safex.Out_entry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:safex.Out_entry)
  return false;
#undef DO_
}

void Out_entry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:safex.Out_entry)
  // optional bytes key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->key(), output);
  }

  // optional bool unlocked = 2;
  if (this->unlocked() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->unlocked(), output);
  }

  // optional uint64 height = 3;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->height(), output);
  }

  // optional bytes txid = 4;
  if (this->txid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->txid(), output);
  }

  // @@protoc_insertion_point(serialize_end:safex.Out_entry)
}

::google::protobuf::uint8* Out_entry::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:safex.Out_entry)
  // optional bytes key = 1;
  if (this->key().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->key(), target);
  }

  // optional bool unlocked = 2;
  if (this->unlocked() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->unlocked(), target);
  }

  // optional uint64 height = 3;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->height(), target);
  }

  // optional bytes txid = 4;
  if (this->txid().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->txid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:safex.Out_entry)
  return target;
}

int Out_entry::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:safex.Out_entry)
  int total_size = 0;

  // optional bytes key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->key());
  }

  // optional bool unlocked = 2;
  if (this->unlocked() != 0) {
    total_size += 1 + 1;
  }

  // optional uint64 height = 3;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->height());
  }

  // optional bytes txid = 4;
  if (this->txid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->txid());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Out_entry::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safex.Out_entry)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Out_entry* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Out_entry>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safex.Out_entry)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safex.Out_entry)
    MergeFrom(*source);
  }
}

void Out_entry::MergeFrom(const Out_entry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safex.Out_entry)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.unlocked() != 0) {
    set_unlocked(from.unlocked());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.txid().size() > 0) {

    txid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.txid_);
  }
}

void Out_entry::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safex.Out_entry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Out_entry::CopyFrom(const Out_entry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safex.Out_entry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Out_entry::IsInitialized() const {

  return true;
}

void Out_entry::Swap(Out_entry* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Out_entry::InternalSwap(Out_entry* other) {
  key_.Swap(&other->key_);
  std::swap(unlocked_, other->unlocked_);
  std::swap(height_, other->height_);
  txid_.Swap(&other->txid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Out_entry::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Out_entry_descriptor_;
  metadata.reflection = Out_entry_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Out_entry

// optional bytes key = 1;
void Out_entry::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Out_entry::key() const {
  // @@protoc_insertion_point(field_get:safex.Out_entry.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Out_entry::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safex.Out_entry.key)
}
 void Out_entry::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safex.Out_entry.key)
}
 void Out_entry::set_key(const void* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safex.Out_entry.key)
}
 ::std::string* Out_entry::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:safex.Out_entry.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Out_entry::release_key() {
  // @@protoc_insertion_point(field_release:safex.Out_entry.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Out_entry::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:safex.Out_entry.key)
}

// optional bool unlocked = 2;
void Out_entry::clear_unlocked() {
  unlocked_ = false;
}
 bool Out_entry::unlocked() const {
  // @@protoc_insertion_point(field_get:safex.Out_entry.unlocked)
  return unlocked_;
}
 void Out_entry::set_unlocked(bool value) {
  
  unlocked_ = value;
  // @@protoc_insertion_point(field_set:safex.Out_entry.unlocked)
}

// optional uint64 height = 3;
void Out_entry::clear_height() {
  height_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 Out_entry::height() const {
  // @@protoc_insertion_point(field_get:safex.Out_entry.height)
  return height_;
}
 void Out_entry::set_height(::google::protobuf::uint64 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:safex.Out_entry.height)
}

// optional bytes txid = 4;
void Out_entry::clear_txid() {
  txid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Out_entry::txid() const {
  // @@protoc_insertion_point(field_get:safex.Out_entry.txid)
  return txid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Out_entry::set_txid(const ::std::string& value) {
  
  txid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safex.Out_entry.txid)
}
 void Out_entry::set_txid(const char* value) {
  
  txid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safex.Out_entry.txid)
}
 void Out_entry::set_txid(const void* value, size_t size) {
  
  txid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safex.Out_entry.txid)
}
 ::std::string* Out_entry::mutable_txid() {
  
  // @@protoc_insertion_point(field_mutable:safex.Out_entry.txid)
  return txid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Out_entry::release_txid() {
  // @@protoc_insertion_point(field_release:safex.Out_entry.txid)
  
  return txid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Out_entry::set_allocated_txid(::std::string* txid) {
  if (txid != NULL) {
    
  } else {
    
  }
  txid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), txid);
  // @@protoc_insertion_point(field_set_allocated:safex.Out_entry.txid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Outs::kOutsFieldNumber;
const int Outs::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Outs::Outs()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:safex.Outs)
}

void Outs::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Outs::Outs(const Outs& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:safex.Outs)
}

void Outs::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  status_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Outs::~Outs() {
  // @@protoc_insertion_point(destructor:safex.Outs)
  SharedDtor();
}

void Outs::SharedDtor() {
  status_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Outs::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Outs::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Outs_descriptor_;
}

const Outs& Outs::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_get_5fouts_2eproto();
  return *default_instance_;
}

Outs* Outs::default_instance_ = NULL;

Outs* Outs::New(::google::protobuf::Arena* arena) const {
  Outs* n = new Outs;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Outs::Clear() {
// @@protoc_insertion_point(message_clear_start:safex.Outs)
  status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  outs_.Clear();
}

bool Outs::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:safex.Outs)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .safex.Out_entry outs = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_outs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_outs()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_outs;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(18)) goto parse_status;
        break;
      }

      // optional string status = 2;
      case 2: {
        if (tag == 18) {
         parse_status:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_status()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->status().data(), this->status().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safex.Outs.status"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:safex.Outs)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:safex.Outs)
  return false;
#undef DO_
}

void Outs::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:safex.Outs)
  // repeated .safex.Out_entry outs = 1;
  for (unsigned int i = 0, n = this->outs_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->outs(i), output);
  }

  // optional string status = 2;
  if (this->status().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status().data(), this->status().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safex.Outs.status");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->status(), output);
  }

  // @@protoc_insertion_point(serialize_end:safex.Outs)
}

::google::protobuf::uint8* Outs::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:safex.Outs)
  // repeated .safex.Out_entry outs = 1;
  for (unsigned int i = 0, n = this->outs_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->outs(i), false, target);
  }

  // optional string status = 2;
  if (this->status().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status().data(), this->status().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safex.Outs.status");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->status(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:safex.Outs)
  return target;
}

int Outs::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:safex.Outs)
  int total_size = 0;

  // optional string status = 2;
  if (this->status().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->status());
  }

  // repeated .safex.Out_entry outs = 1;
  total_size += 1 * this->outs_size();
  for (int i = 0; i < this->outs_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->outs(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Outs::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safex.Outs)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Outs* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Outs>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safex.Outs)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safex.Outs)
    MergeFrom(*source);
  }
}

void Outs::MergeFrom(const Outs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safex.Outs)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  outs_.MergeFrom(from.outs_);
  if (from.status().size() > 0) {

    status_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_);
  }
}

void Outs::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safex.Outs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Outs::CopyFrom(const Outs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safex.Outs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Outs::IsInitialized() const {

  return true;
}

void Outs::Swap(Outs* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Outs::InternalSwap(Outs* other) {
  outs_.UnsafeArenaSwap(&other->outs_);
  status_.Swap(&other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Outs::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Outs_descriptor_;
  metadata.reflection = Outs_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Outs

// repeated .safex.Out_entry outs = 1;
int Outs::outs_size() const {
  return outs_.size();
}
void Outs::clear_outs() {
  outs_.Clear();
}
const ::safex::Out_entry& Outs::outs(int index) const {
  // @@protoc_insertion_point(field_get:safex.Outs.outs)
  return outs_.Get(index);
}
::safex::Out_entry* Outs::mutable_outs(int index) {
  // @@protoc_insertion_point(field_mutable:safex.Outs.outs)
  return outs_.Mutable(index);
}
::safex::Out_entry* Outs::add_outs() {
  // @@protoc_insertion_point(field_add:safex.Outs.outs)
  return outs_.Add();
}
::google::protobuf::RepeatedPtrField< ::safex::Out_entry >*
Outs::mutable_outs() {
  // @@protoc_insertion_point(field_mutable_list:safex.Outs.outs)
  return &outs_;
}
const ::google::protobuf::RepeatedPtrField< ::safex::Out_entry >&
Outs::outs() const {
  // @@protoc_insertion_point(field_list:safex.Outs.outs)
  return outs_;
}

// optional string status = 2;
void Outs::clear_status() {
  status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Outs::status() const {
  // @@protoc_insertion_point(field_get:safex.Outs.status)
  return status_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Outs::set_status(const ::std::string& value) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safex.Outs.status)
}
 void Outs::set_status(const char* value) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safex.Outs.status)
}
 void Outs::set_status(const char* value, size_t size) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safex.Outs.status)
}
 ::std::string* Outs::mutable_status() {
  
  // @@protoc_insertion_point(field_mutable:safex.Outs.status)
  return status_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Outs::release_status() {
  // @@protoc_insertion_point(field_release:safex.Outs.status)
  
  return status_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Outs::set_allocated_status(::std::string* status) {
  if (status != NULL) {
    
  } else {
    
  }
  status_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), status);
  // @@protoc_insertion_point(field_set_allocated:safex.Outs.status)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace safex

// @@protoc_insertion_point(global_scope)
